### ISSUE TITLE
Problems with setting up kivent with python 3.5

### ISSUE THREAD

**Issue by tychovk** [kivy/kivent#137]
Hi everyone,

I've been having problems getting it all to work. I've tried to run both python 2.7 and python 3.5 to see what would and wouldn't work, and apparently this is where it differs:
https://github.com/kivy/kivent/wiki/Getting-Started-2:-Creating-A-GameSystem

```
python setup.py build_ext --inplace
```

Am I missing something, p3.5 support-wise? If not, are there any plans for python 3.5 support?

Thanks!

EDIT:
I've plunged into it a bit more, and I'm guessing it may be _me_. Right now I'm checking the imports where obviously p2 and p3 differ. Specifically in the example refered to above, I get this error:

```
 Traceback (most recent call last):
   File "main_with_cython.py", line 14, in <module>
     from velocity_module.velocity import VelocitySystem2D
 ImportError: /home/diego/python/metamundo/moving_stars/velocity_module/velocity.so: undefined symbol: PyString_Type
```

I'm not even sure what the "velocity" import should refer to, considering 4 files (.pxd, .pyx, .c, .so) after compiling.

**Comment by Kovak** [comment]
What operating system are you using? What are the compilation errors?

**Comment by tychovk** [comment]
OT updated! Thanks for the attention, Kovak. If it helps, I'm using Ubuntu 16.04 LTS. Sorry if it's a very basic issue.

**Comment by Kovak** [comment]
I have not tested anything with python 3.5 yet, I will have to look into this. The velocity import should refer to the .so, the other files are

.pxd -> cython header (equivalent of a C .h)
.pyx -> cython source (equivalent of a C .c)
.c -> The actual .c code generated from the cython source
.so -> The actual compiled code

I do know everything works with py3.4, python 3.5 support will definitely be coming.

**Comment by dummerbd** [comment]
I have a working setup with Ubuntu 16.04 with Python 3.5

I had to setup a virtualenv with Kivy, Cython and the other dependencies installed. I managed my python versions with pyenv so I might my python header files in a different location. If you installed python 3 via `apt-get` you should also try `sudo apt-get install python3-dev` and then run `python3 setup.py build_ext --inplace --force`

**Comment by auvipy** [comment]
sudo -H pip3 install -U git+https://github.com/kivy/kivent.git@master
[sudo] password for asif: 
Collecting git+https://github.com/kivy/kivent.git@master
  Cloning https://github.com/kivy/kivent.git (to master) to /tmp/pip-7cm3b959-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.5/tokenize.py", line 454, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-7cm3b959-build/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-7cm3b959-build/

**Comment by auvipy** [comment]
kivent_cymunk/interaction.pyx:350:24: 'PositionStruct2D' is not a type identifier
Traceback (most recent call last):
  File "setup.py", line 71, in <module>
    cymunk_extensions, cymunk_modules)
  File "setup.py", line 54, in build_extensions_for_modules_cython
    return cythonize(ext_list)
  File "/home/asif/.pyenv/versions/3.5.2/lib/python3.5/site-packages/Cython/Build/Dependencies.py"e
    cythonize_one(*args)
  File "/home/asif/.pyenv/versions/3.5.2/lib/python3.5/site-packages/Cython/Build/Dependencies.py"e
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: kivent_cymunk/interaction.pyx

**Comment by Kovak** [comment]
KivEnt does not work with pip you have to follow the installation instructions as written. The second error appears to be because the kivent_core module is not built.
